version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      SA_PASSWORD: StrongPassword123!
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql  
    networks:
      - cat-net
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P StrongPassword123! -Q "SELECT 1" -C
      interval: 10s
      retries: 10
      timeout: 5s

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./db/init.sql:/init.sql
    command: >
      /bin/bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P StrongPassword123! -i /init.sql -C
      "
    networks:
      - cat-net

  api:
    build: ./api
    container_name: api_container
    env_file:
      - ./api/.env
    depends_on:
      db-init:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    networks:
      - cat-net
    restart: unless-stopped  

networks:
  cat-net:
    driver: bridge

volumes:
  sqlserver_data:  